# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.0.0
      name: Use Node.js 16
      with:
        node-version: '16'
        cache: 'npm'
      
    - name: Installing dependencies
      run: npm i
      
    - name: Building app
      run: CI='' npm run build
