# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: CI='' npm run build
      
      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: cockpit-artifact
          path: build
          retention-days: 1


      
    
  deploy:
  
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - uses: actions/checkout@v2
      - name: Retrieve built package
        uses: actions/download-artifact@v2
        with:
          name: cockpit-artifact
          path: build
    
      - name: LS
        run: ls -R
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: metrograph/cokpit:latest
