# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.0.0
      name: Use Node.js 16
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm i
    - run: CI='' npm run build
    
    - uses: docker/login-action@v1
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - uses: docker/build-push-action@v2
      name: Build and push
      with:
        path: build
        push: true
        tags: metrograph/cockpit:latest
